import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Copy, RadioTower, Send, Trash2, Webhook } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function StreamAnnouncements({ guildId }: { guildId: string }) {
  const channels = trpc.dashboard.channels.useQuery({ guildId }, { enabled: Boolean(guildId) });
  const roles = trpc.dashboard.roles.useQuery({ guildId }, { enabled: Boolean(guildId) });
  const items = trpc.streams.list.useQuery({ guildId }, { enabled: Boolean(guildId) });
  const [name, setName] = useState("إعلان البث"); const [destinationChannelId, setDestinationChannelId] = useState(""); const [mentionRoleId, setMentionRoleId] = useState(""); const [sourceLabel, setSourceLabel] = useState("البث المباشر"); const [sourceUrl, setSourceUrl] = useState(""); const [template, setTemplate] = useState("🔴 **{title}** بدأ البث الآن على {platform}!\n{url}"); const [enabled, setEnabled] = useState(true); const [receiverUrl, setReceiverUrl] = useState<string | null>(null);
  const refresh = () => void items.refetch();
  const create = trpc.streams.create.useMutation({ onSuccess: result => { const url = `${window.location.origin}/api/stream-webhook/${result.id}/${result.secret}`; setReceiverUrl(url); refresh(); toast.success("تم إنشاء رابط الاستقبال السري. انسخه الآن واحفظه في منصة البث."); }, onError: error => toast.error(error.message) });
  const remove = trpc.streams.delete.useMutation({ onSuccess: () => { refresh(); toast.success("تم حذف إعداد إعلان البث"); }, onError: error => toast.error(error.message) });
  const test = trpc.streams.sendTest.useMutation({ onSuccess: () => toast.success("تم إرسال تجربة إلى روم الإعلان"), onError: error => toast.error(error.message) });
  const copy = async (value: string) => { try { await navigator.clipboard.writeText(value); toast.success("تم نسخ الرابط السري"); } catch { toast.error("تعذر النسخ تلقائياً؛ انسخ الرابط يدوياً."); } };
  const input = "h-10 rounded-xl border border-input bg-background/65 px-3 text-sm outline-none focus:ring-2 focus:ring-ring";
  if (!guildId) return null;
  return <section className="guardian-surface rounded-3xl border border-border p-5 sm:p-6"><header className="flex flex-wrap items-start justify-between gap-4 border-b border-border pb-5"><div><div className="flex items-center gap-2 text-xs font-bold tracking-[0.16em] text-rose-300"><RadioTower className="h-4 w-4" />LIVE NOTIFICATIONS</div><h2 className="mt-2 text-xl font-bold">إعلانات البث من رابط عام</h2><p className="mt-1 max-w-2xl text-sm text-muted-foreground">أنشئ رابط استقبال سرياً واربطه في أي منصة أو أداة ترسل Webhook عند بداية البث. لا يُحفظ جسم الطلب الوارد.</p></div><span className="rounded-full bg-rose-400/10 px-3 py-1.5 text-xs font-semibold text-rose-200">منع تكرار تلقائي</span></header>
    <div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="grid gap-3"><label className="grid gap-2 text-sm font-medium">اسم الإعداد<Input value={name} maxLength={96} onChange={event => setName(event.target.value)} /></label><label className="grid gap-2 text-sm font-medium">روم الإعلان<select className={input} value={destinationChannelId} onChange={event => setDestinationChannelId(event.target.value)}><option value="">اختر روم نصي</option>{channels.data?.map(channel => <option value={channel.id} key={channel.id}>#{channel.name}</option>)}</select></label><label className="grid gap-2 text-sm font-medium">رتبة المنشن (اختياري)<select className={input} value={mentionRoleId} onChange={event => setMentionRoleId(event.target.value)}><option value="">بدون منشن رتبة</option>{roles.data?.map(role => <option value={role.id} key={role.id}>@{role.name}</option>)}</select></label><label className="flex items-center justify-between rounded-xl border border-border bg-black/10 px-3 py-2.5 text-sm font-medium">تفعيل إعلان البث<Switch checked={enabled} onCheckedChange={setEnabled} /></label></div>
      <div className="grid gap-3"><label className="grid gap-2 text-sm font-medium">اسم المنصة أو القناة<Input value={sourceLabel} maxLength={80} onChange={event => setSourceLabel(event.target.value)} placeholder="مثال: بث تركي" /></label><label className="grid gap-2 text-sm font-medium">رابط القناة أو المصدر (اختياري)<Input type="url" value={sourceUrl} onChange={event => setSourceUrl(event.target.value)} placeholder="https://…" /></label><label className="grid gap-2 text-sm font-medium">نص الإعلان<Textarea value={template} maxLength={1800} onChange={event => setTemplate(event.target.value)} className="min-h-28" /></label><p className="text-xs text-muted-foreground">المتغيرات: <code>{"{title}"}</code>، <code>{"{url}"}</code>، <code>{"{platform}"}</code>.</p></div></div>
    <div className="mt-5 flex justify-end"><Button disabled={!name.trim() || !destinationChannelId || !sourceLabel.trim() || create.isPending} onClick={() => create.mutate({ guildId, name, enabled, destinationChannelId, mentionRoleId: mentionRoleId || null, sourceLabel, sourceUrl: sourceUrl || undefined, messageTemplate: template || null })}><Webhook className="ml-2 h-4 w-4" />إنشاء رابط استقبال</Button></div>
    {receiverUrl ? <div className="mt-5 rounded-2xl border border-amber-400/25 bg-amber-400/10 p-4"><p className="font-semibold text-amber-100">احفظ هذا الرابط الآن</p><p className="mt-1 text-sm text-amber-100/75">سيُعرض السر بعد الإنشاء فقط. لا تشاركه إلا مع منصة البث أو الأداة التي سترسل الحدث.</p><div className="mt-3 flex gap-2"><Input readOnly value={receiverUrl} className="font-mono text-xs" /><Button variant="outline" onClick={() => void copy(receiverUrl)}><Copy className="h-4 w-4" /></Button></div><p className="mt-3 text-xs text-muted-foreground">صيغة الإرسال: POST JSON يحتوي <code>title</code> و<code>url</code> برابط HTTPS، واختيارياً <code>eventId</code> و<code>thumbnailUrl</code>.</p></div> : null}
    <div className="mt-6 grid gap-3">{items.data?.map(item => <article className="flex flex-wrap items-center gap-3 rounded-2xl border border-border bg-black/10 p-4" key={item.id}><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-rose-400/10 text-rose-300"><RadioTower className="h-5 w-5" /></div><div className="min-w-0 flex-1"><p className="font-semibold">{item.name}</p><p className="mt-1 truncate text-sm text-muted-foreground">{item.sourceLabel} → #{channels.data?.find(channel => channel.id === item.destinationChannelId)?.name ?? item.destinationChannelId}</p></div><span className={item.enabled ? "rounded-full bg-emerald-400/10 px-2.5 py-1 text-xs text-emerald-300" : "rounded-full bg-muted px-2.5 py-1 text-xs text-muted-foreground"}>{item.enabled ? "مفعّل" : "متوقف"}</span><Button variant="outline" size="sm" disabled={test.isPending} onClick={() => test.mutate({ guildId, id: item.id })}><Send className="ml-1 h-3.5 w-3.5" />تجربة</Button><Button variant="outline" size="icon" className="text-destructive" disabled={remove.isPending} onClick={() => remove.mutate({ guildId, id: item.id })} aria-label="حذف إعداد إعلان البث"><Trash2 className="h-4 w-4" /></Button></article>)}{items.data?.length === 0 ? <p className="rounded-2xl border border-dashed border-border p-5 text-center text-sm text-muted-foreground">ما أضفت إعداد بث بعد. أنشئ رابطاً سرياً من النموذج أعلاه.</p> : null}</div>
  </section>;
}
