import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Image, Paintbrush, RotateCcw, Save, Send, SlidersHorizontal, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

type CardConfig = {
  heading: string; subheading: string; memberLine: string; accentColor: string; backgroundColor: string;
  backgroundPreset: "aurora" | "midnight" | "royal" | "ember"; avatarShape: "circle" | "rounded";
  avatarSize: number; headingSize: number; subheadingSize: number; headingFont: "sans" | "serif"; bodyFont: "sans" | "serif"; contentOffsetY: number; backgroundImageUrl: string | null; logoUrl: string | null;
};

const defaults: CardConfig = { heading: "ياهلا {user}", subheading: "نورت مجتمع {server}", memberLine: "أنت العضو #{memberCount}", accentColor: "#8B5CF6", backgroundColor: "#111827", backgroundPreset: "aurora", avatarShape: "circle", avatarSize: 132, headingSize: 46, subheadingSize: 24, headingFont: "sans", bodyFont: "sans", contentOffsetY: 0, backgroundImageUrl: null, logoUrl: null };
const safeConfig = (raw?: string | null): CardConfig => { try { return { ...defaults, ...(raw ? JSON.parse(raw) : {}) } as CardConfig; } catch { return defaults; } };
const interpolate = (value: string, guildName: string) => value.replaceAll("{user}", "عضو جديد").replaceAll("{server}", guildName).replaceAll("{memberCount}", "1,284");

function Range({ label, value, min, max, onChange }: { label: string; value: number; min: number; max: number; onChange: (value: number) => void }) {
  return <label className="grid gap-2 text-sm font-medium"><span className="flex items-center justify-between text-muted-foreground"><span>{label}</span><b className="text-foreground">{value}</b></span><input type="range" min={min} max={max} value={value} onChange={event => onChange(Number(event.target.value))} className="accent-violet-400" /></label>;
}

export default function WelcomeStudio({ guildId, guildName }: { guildId: string; guildName: string }) {
  const settings = trpc.settings.get.useQuery({ guildId }, { enabled: Boolean(guildId) });
  const channels = trpc.dashboard.channels.useQuery({ guildId }, { enabled: Boolean(guildId) });
  const roles = trpc.dashboard.roles.useQuery({ guildId }, { enabled: Boolean(guildId) });
  const [enabled, setEnabled] = useState(false); const [channelId, setChannelId] = useState(""); const [autoRoleId, setAutoRoleId] = useState(""); const [memberCountChannelId, setMemberCountChannelId] = useState(""); const [message, setMessage] = useState("مرحباً {user} في {server}!"); const [config, setConfig] = useState<CardConfig>(defaults);
  useEffect(() => { if (settings.data) { setEnabled(settings.data.welcomeEnabled); setChannelId(settings.data.welcomeChannelId ?? ""); setAutoRoleId(settings.data.welcomeAutoRoleId ?? ""); setMemberCountChannelId(settings.data.memberCountChannelId ?? ""); setMessage(settings.data.welcomeMessage ?? "مرحباً {user} في {server}!"); setConfig(safeConfig(settings.data.welcomeCardConfig)); } }, [settings.data]);
  const save = trpc.settings.save.useMutation({ onSuccess: () => { void settings.refetch(); toast.success("تم حفظ استوديو الترحيب"); }, onError: error => toast.error(error.message) });
  const sendPreview = trpc.welcome.sendPreview.useMutation({ onSuccess: () => toast.success("أُرسلت البطاقة إلى قناة الترحيب"), onError: error => toast.error(error.message) });
  const update = <K extends keyof CardConfig>(key: K, value: CardConfig[K]) => setConfig(current => ({ ...current, [key]: value }));
  const saveSettings = () => save.mutate({ guildId, guildName, welcomeEnabled: enabled, welcomeChannelId: channelId || null, welcomeAutoRoleId: autoRoleId || null, memberCountChannelId: memberCountChannelId || null, welcomeMessage: message, welcomeCardConfig: JSON.stringify(config) });
  if (!guildId) return <section className="guardian-surface rounded-2xl border border-border p-8 text-center text-muted-foreground">اختر سيرفراً متصلاً أولاً لفتح استوديو الترحيب.</section>;
  const background = config.backgroundImageUrl ? `linear-gradient(135deg, ${config.backgroundColor}CC, #080A12AA), url(${config.backgroundImageUrl}) center / cover` : `linear-gradient(135deg, ${config.backgroundColor}, ${config.backgroundPreset === "ember" ? "#9A3412" : config.backgroundPreset === "royal" ? "#4C1D95" : config.backgroundPreset === "midnight" ? "#09090B" : "#1D4ED8"})`;
  return <section className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_minmax(400px,0.9fr)]">
    <div className="guardian-surface rounded-3xl border border-border p-5 sm:p-6">
      <header className="flex flex-wrap items-start justify-between gap-4 border-b border-border pb-5"><div><div className="flex items-center gap-2 text-xs font-bold tracking-[0.16em] text-violet-300"><Sparkles className="h-4 w-4" />WELCOME STUDIO</div><h2 className="mt-2 text-xl font-bold">تصميم استقبال العضو الجديد</h2><p className="mt-1 max-w-2xl text-sm text-muted-foreground">اضبط البطاقة في اللوحة؛ البوت يطبّق قيوداً على الألوان والأحجام وروابط HTTPS قبل الإرسال.</p></div><Switch checked={enabled} onCheckedChange={setEnabled} aria-label="تفعيل الترحيب المصوّر" /></header>
      <div className="mt-5 grid gap-5">
        <div className="grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm font-medium">قناة الترحيب<select value={channelId} onChange={event => setChannelId(event.target.value)} className="h-10 rounded-xl border border-input bg-background/65 px-3 text-sm"><option value="">اختر قناة نصية</option>{channels.data?.map(channel => <option value={channel.id} key={channel.id}>#{channel.name}</option>)}</select></label><label className="grid gap-2 text-sm font-medium">قناة عداد الأعضاء<select value={memberCountChannelId} onChange={event => setMemberCountChannelId(event.target.value)} className="h-10 rounded-xl border border-input bg-background/65 px-3 text-sm"><option value="">لا تحدّث عداداً</option>{channels.data?.map(channel => <option value={channel.id} key={channel.id}>#{channel.name}</option>)}</select><span className="text-xs font-normal text-muted-foreground">سيغيّر مجلساوي اسمها إلى عدد أعضاء السيرفر عند الدخول والخروج.</span></label><label className="grid gap-2 text-sm font-medium">رتبة تلقائية للعضو الجديد<select value={autoRoleId} onChange={event => setAutoRoleId(event.target.value)} className="h-10 rounded-xl border border-input bg-background/65 px-3 text-sm"><option value="">لا تمنح رتبة</option>{roles.data?.map(role => <option value={role.id} key={role.id}>@{role.name}</option>)}</select><span className="text-xs font-normal text-muted-foreground">مجلساوي يرفض تلقائياً أي رتبة إدارة أو صلاحية مرتفعة.</span></label><label className="grid gap-2 text-sm font-medium">شكل الصورة<select value={config.avatarShape} onChange={event => update("avatarShape", event.target.value as CardConfig["avatarShape"])} className="h-10 rounded-xl border border-input bg-background/65 px-3 text-sm"><option value="circle">دائري</option><option value="rounded">مربع بحواف دائرية</option></select></label></div>
        <div className="grid gap-3 rounded-2xl border border-white/5 bg-black/10 p-4"><div className="flex items-center gap-2 font-semibold"><Paintbrush className="h-4 w-4 text-violet-300" />المحتوى</div><label className="grid gap-2 text-sm">العنوان<Input value={config.heading} maxLength={120} onChange={event => update("heading", event.target.value)} /></label><label className="grid gap-2 text-sm">العنوان الفرعي<Input value={config.subheading} maxLength={180} onChange={event => update("subheading", event.target.value)} /></label><label className="grid gap-2 text-sm">سطر العضوية<Input value={config.memberLine} maxLength={120} onChange={event => update("memberLine", event.target.value)} /></label><label className="grid gap-2 text-sm">رسالة Discord المصاحبة<Textarea value={message} maxLength={1800} onChange={event => setMessage(event.target.value)} className="min-h-20" /></label><p className="text-xs text-muted-foreground">الرموز المدعومة: <code>{"{user}"}</code>، <code>{"{server}"}</code>، <code>{"{memberCount}"}</code>.</p></div>
        <div className="grid gap-4 rounded-2xl border border-white/5 bg-black/10 p-4 md:grid-cols-2"><div className="grid gap-3"><div className="flex items-center gap-2 font-semibold md:col-span-2"><Image className="h-4 w-4 text-violet-300" />الخلفية والهوية</div><label className="grid gap-2 text-sm">لون التمييز<Input type="color" value={config.accentColor} onChange={event => update("accentColor", event.target.value)} className="h-10 p-1" /></label><label className="grid gap-2 text-sm">لون الخلفية<Input type="color" value={config.backgroundColor} onChange={event => update("backgroundColor", event.target.value)} className="h-10 p-1" /></label></div><div className="grid gap-3"><label className="grid gap-2 text-sm">النمط<select value={config.backgroundPreset} onChange={event => update("backgroundPreset", event.target.value as CardConfig["backgroundPreset"])} className="h-10 rounded-xl border border-input bg-background/65 px-3 text-sm"><option value="aurora">Aurora</option><option value="midnight">Midnight</option><option value="royal">Royal</option><option value="ember">Ember</option></select></label><label className="grid gap-2 text-sm">رابط خلفية HTTPS اختياري<Input type="url" value={config.backgroundImageUrl ?? ""} onChange={event => update("backgroundImageUrl", event.target.value || null)} placeholder="https://…" /></label><label className="grid gap-2 text-sm">رابط الشعار HTTPS اختياري<Input type="url" value={config.logoUrl ?? ""} onChange={event => update("logoUrl", event.target.value || null)} placeholder="https://…" /></label></div></div>
        <div className="grid gap-4 rounded-2xl border border-white/5 bg-black/10 p-4 md:grid-cols-2"><div className="flex items-center gap-2 font-semibold md:col-span-2"><SlidersHorizontal className="h-4 w-4 text-violet-300" />الخط والمقاسات والمحاذاة</div><label className="grid gap-2 text-sm">خط العنوان<select value={config.headingFont} onChange={event => update("headingFont", event.target.value as CardConfig["headingFont"])} className="h-10 rounded-xl border border-input bg-background/65 px-3 text-sm"><option value="sans">Sans واضح</option><option value="serif">Serif رسمي</option></select></label><label className="grid gap-2 text-sm">خط النص<select value={config.bodyFont} onChange={event => update("bodyFont", event.target.value as CardConfig["bodyFont"])} className="h-10 rounded-xl border border-input bg-background/65 px-3 text-sm"><option value="sans">Sans واضح</option><option value="serif">Serif رسمي</option></select></label><Range label="حجم العنوان" value={config.headingSize} min={24} max={72} onChange={value => update("headingSize", value)} /><Range label="حجم النص الفرعي" value={config.subheadingSize} min={14} max={42} onChange={value => update("subheadingSize", value)} /><Range label="حجم صورة العضو" value={config.avatarSize} min={72} max={180} onChange={value => update("avatarSize", value)} /><Range label="إزاحة المحتوى" value={config.contentOffsetY} min={-100} max={100} onChange={value => update("contentOffsetY", value)} /></div>
      </div>
      <footer className="mt-6 flex flex-wrap justify-end gap-3 border-t border-border pt-5"><Button variant="outline" onClick={() => setConfig(defaults)}><RotateCcw className="ml-2 h-4 w-4" />استعادة الافتراضي</Button><Button variant="outline" disabled={!channelId || sendPreview.isPending} onClick={() => sendPreview.mutate({ guildId })}><Send className="ml-2 h-4 w-4" />اختبار المحفوظ</Button><Button disabled={save.isPending} onClick={saveSettings}><Save className="ml-2 h-4 w-4" />حفظ الاستوديو</Button></footer>
    </div>
    <aside className="guardian-surface sticky top-5 h-fit rounded-3xl border border-border p-5"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-bold tracking-[0.16em] text-muted-foreground">LIVE PREVIEW</p><h2 className="mt-1 font-bold">معاينة البطاقة</h2></div><span className="rounded-full bg-emerald-400/10 px-2.5 py-1 text-xs font-semibold text-emerald-300">{enabled ? "مفعّل" : "متوقف"}</span></div><div className="relative overflow-hidden rounded-3xl border p-4 shadow-2xl" style={{ background, borderColor: `${config.accentColor}99` }}><div className="absolute inset-0 bg-black/15" /><div className="relative flex min-h-[430px] flex-col items-center justify-center text-center" style={{ transform: `translateY(${config.contentOffsetY * 0.35}px)` }}><div className="flex h-11 w-11 items-center justify-center overflow-hidden text-lg font-black text-white" style={{ backgroundColor: config.accentColor, borderRadius: config.avatarShape === "circle" ? "9999px" : "14px" }}>{config.logoUrl ? <img src={config.logoUrl} className="h-full w-full object-cover" alt="شعار" /> : "م"}</div><div className="mt-9 grid place-items-center border-4 bg-slate-800 text-4xl font-black text-white" style={{ width: config.avatarSize * 0.88, height: config.avatarSize * 0.88, borderColor: config.accentColor, borderRadius: config.avatarShape === "circle" ? "9999px" : "24px" }}>ع</div><p className="mt-7 text-white/75" style={{ fontSize: config.subheadingSize * 0.63 }}>{interpolate(config.subheading, guildName)}</p><h3 className="mt-2 font-black text-white" style={{ fontSize: config.headingSize * 0.72 }}>{interpolate(config.heading, guildName)}</h3><div className="my-5 h-0.5 w-48" style={{ backgroundColor: config.accentColor }} /><p className="font-bold text-white" style={{ fontSize: 20 }}>{interpolate(config.memberLine, guildName)}</p><p className="mt-4 text-xs text-white/70">{message.replaceAll("{user}", "@عضو جديد").replaceAll("{server}", guildName)}</p></div></div><p className="mt-4 text-xs leading-5 text-muted-foreground">المعاينة توضح الترتيب؛ البطاقة المرسلة PNG عالية الجودة وتأخذ صورة العضو الفعلية تلقائياً.</p></aside>
  </section>;
}
